prompts:
- prompts.txt
providers:
- openai:gpt-3.5-turbo-0613
tests:
- assert:
  - type: llm-rubric
    value: "Inneh\xE5ller pneumoni"
  description: This a simulated question from a patient
  vars:
    background: '\"{''patient_id'': 123123, ''aktivitet_id'': 59492, ''aktivitettyp'':
      ''slutanteckning, l\u00e4kare'', ''v\u00e5rdgivare'': ''August B. Carlsson'',
      ''v\u00e5rdgivarekategori'': ''L\u00c4K'', ''v\u00e5rdgivaretel'': ''031-123456'',
      ''f\u00f6rvaltning'': ''SU'', ''verksamhet'': ''Medicinalavdelning X'', ''plats'':
      ''Avdelning 357 Medicin \u00d6stra'', ''startdatum'': ''2020-03-28'', ''slutdatum'':
      ''2020-03-30'', ''huvuddiagnos'': ''J189 Pneumoni, ospecificerad'', ''anamnes'':
      ''feber, hosta och l\u00e5gt blodtryck'', ''socialt'': ''pension\u00e4r, tidigare
      industriarbetare'', ''tidigare_sjukdomar'': ''Kolecystekomerad 2010. Tidigare
      r\u00f6kare.'', ''nuvarande_sjukdomar'': ''Hypertoni. Atros. Dyspepsi.'', ''aktuellt'':
      ''Inkommer med tv\u00e5 dagars anamnes p\u00e5 feber och hosta. Hypoton och
      f\u00f6rh\u00f6jd andningsfrekvens vid inkomst. CABR 2. Lungrtg med h\u00f6gersidiga
      infiltrat. CRP 270.'', ''sammanfattning'': ''Initieras p\u00e5 bensylpc 3gx3
      och st\u00f6tdos Nebcina tillsammans med v\u00e4tska. Initial syrgaskr\u00e4vande.
      F\u00f6rb\u00e4ttras p\u00e5 inslagen behandling. Feberfri sedan 29/3, syrgas
      avvecklas. CRP mer \u00e4n halverad 30/3. \u00d6vers\u00e4tts samma dag p\u00e5
      peroral behandling med fenoximetylpc'', ''bed\u00f6mning'': ''Bakteriell pneumoni.
      Oklart agens, blododlingar negativa. Svarar bra p\u00e5 bensylpc'', ''planering'':
      ''Fortsatt behandling med antibiotika i totalt 7 dagar till och me 4/3. Initieras
      p\u00e5 fenoxmetylpc x 3 vid hemkomst.'', ''fr\u00e5n_plats'': ''HEM'', ''till_plats'':
      ''HEM''}\"'
    id: 123213
    input: Vad var min observerade diagnos?
- assert:
  - type: llm-rubric
    value: "Innehåller paracetamol och ibuprofen"
  description: This a simulated question from a patient
  vars:
    background: '{
      "patient_id": 112200,
      "aktivitet_id": 99887766,
      "läkemedel": "Smärtstillande",
      "substans": "Paracetamol",
      "kategori": "Analgetika",
      "atc_kod": "N02BE01",
      "beredningsform": "Tablett",
      "dosering": "500 mg vid behov, max 4 gånger dagligen",
      "styrka": "500",
      "styrka_enhet": "mg",
      "vårdgivare": "Eva Eriksson",
      "vårdgivarekategori": "LÄK",
      "vårdgivaretel": "08-112200",
      "verksamhet": "Ortopedimottagning",
      "förmån": "Y",
      "förskrivningsdatum": "2023-06-01",
      "giltigt_till_och_med": "2023-06-08",
      "senast_uttag": "-",
      "tidigast_uttag_inom_förmån": "2023-06-01",
      "förskriven_mängd": 40,
      "senast_uttagen_mängd": 0,
      "återstående_mängd": 40,
      "uttag_antal": 0,
      "uttag_kvar": 0
    },
    {
      "patient_id": 112200,
      "aktivitet_id": 876,
      "läkemedel": "Antiinflammatoriskt",
      "substans": "Ibuprofen",
      "kategori": "Antiinflammatoriska och antireumatiska medel",
      "atc_kod": "M01AE01",
      "beredningsform": "Tablett",
      "dosering": "400 mg vid behov, max 3 gånger dagligen",
      "styrka": "400",
      "styrka_enhet": "mg",
      "vårdgivare": "Eva Eriksson",
      "vårdgivarekategori": "LÄK",
      "vårdgivaretel": "08-112200",
      "verksamhet": "Ortopedimottagning",
      "förmån": "Y",
      "förskrivningsdatum": "2023-06-01",
      "giltigt_till_och_med": "2023-06-08",
      "senast_uttag": "-",
      "tidigast_uttag_inom_förmån": "2023-06-01",
      "förskriven_mängd": 30,
      "senast_uttagen_mängd": 0,
      "återstående_mängd": 30,
      "uttag_antal": 0,
      "uttag_kvar": 0
    }'
    id: 112200
    input: Vilka läkemedel tar patienten?
