credentials:
  usernames:
    # Medical Staff
    oskarpauli:
      email: oskarpauli@gmail.com
      name: 'Oskar Pauli' 
      password: $2b$12$H811Om3K0jLjDLcVPHjCdeEtssUsZUZGbxcqUwEyj97wPinkbTpq6
      patients: ['123123','112200','112266','112233','112299','112244']
      status: "Doctor"
    felixnilsson:
      email: felixnilsson@gmail.com
      name: 'Felix Nilsson' 
      password: $2b$12$H811Om3K0jLjDLcVPHjCdeEtssUsZUZGbxcqUwEyj97wPinkbTpq6
      patients: ['123456','112211','112277','789012','987321']
      status: "Doctor"
    henrikjohansson:
      email: henrikjohansson@gmail.com
      name: 'Henrik Johansson' 
      password: $2b$12$H811Om3K0jLjDLcVPHjCdeEtssUsZUZGbxcqUwEyj97wPinkbTpq6
      patients: ['654321','654322','112222','112288','112255']
      status: "Doctor"
    # Patients (extensible!)
    p123123:
      email: 123123@gmail.com
      name: '123123' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['123123']
      status: "Patient"
    p123456:
      email: 123456@gmail.com
      name: '123456' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['123456']
      status: "Patient"
    p654322:
      email: 654322@gmail.com
      name: '654322' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['654322']
      status: "Patient"
    p654322:
      email: 654322@gmail.com
      name: '654322' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['654322']
      status: "Patient"
    p654322:
      email: 654322@gmail.com
      name: '654322' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['654322']
      status: "Patient"
    p654322:
      email: 654322@gmail.com
      name: '654322' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['654322']
      status: "Patient"
    p654322:
      email: 654322@gmail.com
      name: '654322' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['654322']
      status: "Patient"
    p654322:
      email: 654322@gmail.com
      name: '654322' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['654322']
      status: "Patient"
    p654322:
      email: 654322@gmail.com
      name: '654322' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['654322']
      status: "Patient"
    p654322:
      email: 654322@gmail.com
      name: '654322' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['654322']
      status: "Patient"
    p654321:
      email: 654321@gmail.com
      name: '654321' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['654321']
      status: "Patient"
    p654322:
      email: 654322@gmail.com
      name: '654322' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['654322']
      status: "Patient"
    p789012:
      email: 789012@gmail.com
      name: '789012' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['789012']
      status: "Patient"
    p987321:
      email: 987321@gmail.com
      name: '987321' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['987321']
      status: "Patient"
    p112200:
      email: 112200@gmail.com
      name: '112200' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['112200']
      status: "Patient"
    p112211:
      email: 112211@gmail.com
      name: '112211' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['112211']
      status: "Patient"
    p112222:
      email: 112222@gmail.com
      name: '112222' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['112222']
      status: "Patient"
    p112233:
      email: 112233@gmail.com
      name: '112233' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['112233']
      status: "Patient"
    p112244:
      email: 112244@gmail.com
      name: '112244' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['112244']
      status: "Patient"
    p112255:
      email: 112255@gmail.com
      name: '112255' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['112255']
      status: "Patient"
    p112266:
      email: 112266@gmail.com
      name: '112266' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['112266']
      status: "Patient"
    p112277:
      email: 112277@gmail.com
      name: '112277' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['112277']
      status: "Patient"
    p112288:
      email: 112288@gmail.com
      name: '112288' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['112288']
      status: "Patient"
    p112299:
      email: 112299@gmail.com
      name: '112299' 
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
      patients: ['112299']
      status: "Patient"
cookie:
  expiry_days: 0
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com

