credentials:
  usernames:
    augustcarlsson:
      email: augustcarlsson@gmail.com
      name: 'August Carlsson' 
      password: $2b$12$H811Om3K0jLjDLcVPHjCdeEtssUsZUZGbxcqUwEyj97wPinkbTpq6
      patients: ['123123','123456']
    annaandersson:
      email: annaandersson@gmail.com
      name: 'Anna Andersson' 
      password: $2b$12$H811Om3K0jLjDLcVPHjCdeEtssUsZUZGbxcqUwEyj97wPinkbTpq6
      patients: ['123123','123456']
    mariaandersson:
      email: mariaandersson@gmail.com
      name: 'Maria Andersson' 
      password: $2b$12$H811Om3K0jLjDLcVPHjCdeEtssUsZUZGbxcqUwEyj97wPinkbTpq6
      patients: ['654321','654322']
    evakarlsson:
      email: evakarlsson@gmail.com
      name: 'Eva Karlsson' 
      password: $2b$12$H811Om3K0jLjDLcVPHjCdeEtssUsZUZGbxcqUwEyj97wPinkbTpq6
      patients: ['654321','654322']
    evajohansson:
      email: evajohansson@gmail.com
      name: 'Eva Johansson' 
      password: $2b$12$H811Om3K0jLjDLcVPHjCdeEtssUsZUZGbxcqUwEyj97wPinkbTpq6
      patients: ['789012','987321']
    larssvensson:
      email: larssvensson@gmail.com
      name: 'Lars Svensson' 
      password: $2b$12$H811Om3K0jLjDLcVPHjCdeEtssUsZUZGbxcqUwEyj97wPinkbTpq6
      patients: ['789012','987321']
cookie:
  expiry_days: 0
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com

