credentials:
  usernames:
    jsmith:
      email: jsmith@gmail.com
      name: John Smith
      password: $2b$12$AfmoTVBMoCNOWsLfLWoqbuwyAwCx7Rj9FJqo7kn.c8rvhc01TrZ2.
    rbriggs:
      email: rbriggs@gmail.com
      name: Rebecca Briggs
      password: $2b$12$sGwABPvW5UnSIxXk6yQ/AugfMo3jFkb4ZyOJnkUpcxGrI1g68qsPq
cookie:
  expiry_days: 30
  key: some_signature_key # Must be string
  name: some_cookie_name
preauthorized:
  emails:
  - melsby@gmail.com

