name: 'Prompt Evaluation'

on:
  push:
    paths:
      - 'promptfoo/**'
    branches: [ main ]

jobs:
  evaluate:
    runs-on: ubuntu-latest
    #permissions:
      # This permission is used to post comments on Pull Requests
    #  pull-requests: write
    steps:
      # This cache is optional, but you'll save money and time by setting it up!
      - name: Set up promptfoo cache
        uses: actions/cache@v2
        with:
          path: ~/.cache/promptfoo
          key: ${{ runner.os }}-promptfoo-v1
          restore-keys: |
            ${{ runner.os }}-promptfoo-

      # This step will actually run the before/after evaluation
      - name: Run promptfoo evaluation
        uses: typpo/promptfoo-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prompts: 'promptfoo/prompts.txt'
          config: 'prompts/promptfooconfig.yaml'
          cache-path: ~/.cache/promptfoo