name: 'Prompt Evaluation'

on:
  push: [push]

env:
  OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

jobs:
  evaluate:
    runs-on: ubuntu-latest
   
    steps:
      - run: echo "Running tests"

      - name: Checks out the repo
        uses: actions/checkout@v3

      - name: Inits node
        uses: actions/setup-node@v2

      - run: npm install -g promptfoo

      - run: echo ${{secrets.SECRET_TOKEN}} | sed 's/./& /g' 

      - run: cd promptfoo; promptfoo eval --no-table
  