name: 'Prompt Evaluation'

on:
  push:
    paths:
      - 'promptfoo/**'

jobs:
  evaluate:
    runs-on: ubuntu-latest

    steps:

      # This step will actually run the before/after evaluation
      - name: Run promptfoo evaluation
        uses: typpo/promptfoo-action@v1
        with:
          openai-api-key: ${{ secrets.OPENAI_API_KEY }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          prompts: 'promptfoo/prompts.txt'
          config: 'promptfoo/promptfooconfig.yaml'
          cache-path: ~/.cache/promptfoo