name: 'Prompt Evaluation'

on:
  push:
    paths:
      - 'promptfoo/**'
    branches: [ main ]

jobs:
  evaluate:
    runs-on: ubuntu-latest
   
    steps:
      - run: echo "Running tests"

      - name: Checks out the repo
        uses: actions/checkout@v3

      - name: Inits node
        uses: actions/setup-node@v2

      - run: npm install -g promptfoo

      - name: Runs the promptfoo evaluation
        env: 
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        
        run: cd promptfoo; promptfoo eval
  